export const lawyerSpecialties = [
  "All areas",
  "Actions against the police - legal aid",
  "Administrative and public law",
  "Advocacy",
  "Agriculture",
  "Aviation",
  "Banking",
  "Benefits and allowances",
  "Charities",
  "Children",
  "Clinical negligence",
  "Commercial litigation",
  "Commercial property",
  "Community care - legal aid",
  "Company / commercial - small businesses",
  "Company and commercial",
  "Construction",
  "Consumer",
  "Consumer - financial services",
  "Consumer - goods and services",
  "Consumer - utilities",
  "Contract",
  "Conveyancing - residential",
  "Corporate finance",
  "Crime - domestic violence",
  "Crime - fraud",
  "Crime - general",
  "Crime - juvenile",
  "Crime - legal aid",
  "Crime - motoring",
  "Crime - sex",
  "Cross-border",
  "Debt and bankruptcy - personal",
  "Debt recovery",
  "Defamation",
  "Dispute resolution - civil mediation",
  "Dispute resolution - commercial mediation",
  "Education",
  "Elderly care",
  "Elderly care home fees",
  "Employment",
  "Energy and natural resources",
  "Environment",
  "European Community law",
  "Family - divorce and separation",
  "Family - general",
  "Family - legal aid",
  "Family - marriage and civil partnerships",
  "Family - mediation",
  "Family - mediation - legal aid",
  "Family public law - legal aid",
  "Financial services",
  "Human rights",
  "Immigration - asylum",
  "Immigration - asylum - legal aid",
  "Immigration - general",
  "Immigration - general - legal aid",
  "Immigration - nationality and citizenship",
  "Information Technology",
  "Insolvency and restructuring - business",
  "Insurance",
  "Intellectual property",
  "Judicial review",
  "Judicial review - legal aid",
  "Landlord and tenant - commercial",
  "Landlord and tenant - residential",
  "Lasting power of attorney",
  "Licensing gaming and betting",
  "Litigation - general",
  "Litigation - small claims",
  "Litigation - tickets and fines",
  "LPA - Health and Welfare",
  "LPA - Property and Affairs",
  "Maritime and shipping",
  "Media, entertainment and sport",
  "Mental health",
  "Mental health - legal aid",
  "Mergers and acquisitions",
  "Military",
  "Neighbor disputes",
  "Pensions",
  "Personal injury",
  "Personal injury - RTA",
  "Planning",
  "Prison law - legal aid",
  "Private client - disputed probate",
  "Private client - disputed trusts",
  "Private client - disputed wills",
  "Private client - international",
  "Private client - Probate",
  "Private client - trusts",
  "Private client - Wills",
  "Professional negligence",
  "Tax",
  "Tax - Company and commercial",
  "Tax - Employment",
  "Tax - Employment/HR",
  "Tax - Money and debt",
  "Tax - personal",
  "Travel and tourism",
];
